force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TradesControllerTest.cls
@IsTest
public with sharing class TradesControllerTest {
    @IsTest
    static void testIfTradeCreated() {
      //Arrange
      Decimal sellAmount = 100.00;
      String sellCurrency = 'BAM';
      Decimal buyAmount = 100.00;
      String buyCurrency = 'BAM';
      Decimal rate = 1.0000;

      //Act
      TradesController.createTrade(sellAmount, sellCurrency, buyAmount, buyCurrency, rate);
      List<Trade__c> insertedTrades = [SELECT Sell_Amount__c FROM Trade__c WHERE Sell_Amount__c = 100.00];

      //Assert
      System.assertEquals(true, insertedTrades.size() > 0);
    }
  
    @isTest
    static void testTradeSelector(){
       //Arrange
       Trade__c testTrade = new Trade__c();
       insert testTrade;
 
       //Act
       List<Trade__c> tradesList = TradesController.getTradesList();
       
       //Assert
       System.assertEquals(true, tradesList.size() > 0);
    }
}